### ISSUE TITLE
ブランチ関係の整理

### ISSUE THREAD

**Issue by k-yoshimi** [k-yoshimi/Komega#13]
@ykonishi 
現在、ブランチが色々と散ってしまっているので、いったんmergeなどをして整理したいのですが、一度相談できるでしょうか？

**Comment by k-yoshimi** [comment]
やっているときはいいのですが、大抵放置にすると、あとで何をやっていたかわからなくなります。キリがいいところで、一気に行った方がいいかと思ってます。

**Comment by ykonishi** [comment]
吉見様
@k-yoshimi 

ブランチが散ってしまっている問題に関して、承知いたしました。
こちらで作成したブランチについては以下のようになっています。

- qmr: Shifted QMR sym法を実装したバージョン

- qmr-devel: Shifted QMR sym実装バージョンの開発版（現在はここを主に修正）

- residual-plot: 残差プロット用のブランチ

qmr-develをqmrにマージして削除するのが良いのではないかと考えております。
residual-plotをどうするかが悩みどころです。

上記お時間のある時にでもご相談させていただければ幸いです。

**Comment by k-yoshimi** [comment]
@ykonishi さま
そろそろKωのバージョンを上げてリリースできればと思っております。
それに向けて色々と整理できればと考えています。
まずはブランチの件についてお伺いしたいのですが、現状はどのようになっているでしょうか？
また、マニュアル等についても現状の整備状況を合わせて、ご報告いただければ幸いです。
お手数ですがよろしくお願いいたします。

**Comment by ykonishi** [comment]
吉見様、
@k-yoshimi
 
こちらの方、少し間隔が空いてしまい申し訳ありません。
基本的にはブランチはqmr-develが最新という事で、上記と状況に変化はありません。
またマニュアル等含めてこちらで状況を整理して改めてご報告差し上げます。
どうぞよろしくお願いいたします。

**Comment by k-yoshimi** [comment]
@ykonishi さま
承知しました。時間のある時にまとめて作業をしてしまった方が良さそうですね。
ライブラリ化については問題なく行えているという認識で問題ないでしょうか？

**Comment by k-yoshimi** [comment]
masterとgh-pagesのみになったので、一旦closeします。
