### ISSUE TITLE
アプリ：並列化効率の確認

### ISSUE THREAD

**Issue by k-yoshimi** [k-yoshimi/Komega#5]
CMRで早くなっているかの確認(スレッド並列、MPI並列)。

**Comment by k-yoshimi** [comment]
マニュアルにも手法とアルゴリズム、参考文献を掲載しておく。

**Comment by ykonishi** [comment]
ライブラリのマニュアルにアルゴリズムと参考文献の記述を追加。
https://github.com/k-yoshimi/Komega/blob/qmr-devel/doc/library/ja
https://github.com/k-yoshimi/Komega/tree/qmr-devel/doc/library/en

**Comment by ykonishi** [comment]
TODO
- 並列化効率を確認
- アルゴリズムの特徴に関して記述を追加

**Comment by k-yoshimi** [comment]
@ykonishi 
usageにqmrなどが抜けていたりする気がします。
