### ISSUE TITLE
アプリ：手法選択機能

### ISSUE THREAD

**Issue by k-yoshimi** [k-yoshimi/Komega#7]
入力ファイルから手法を選べるようにする。
デフォルトはauto.

**Comment by k-yoshimi** [comment]
```
&cg
method = "bicg"
```
のような感じにする。デフォルトはauto。

**Comment by ykonishi** [comment]
作業内容
- shiftk_vals.F90でmethodを定義（→ shiftk_vals.F90に定義されているsolver変数を使用）
- shiftk_io.F90のinput_parameter_cgを修正

**Comment by ykonishi** [comment]
上記機能を追加しました。
https://github.com/k-yoshimi/Komega/tree/qmr-devel

```
&cg
method = "bicg" | "cocg" | "shifted_qmr_sym" | "shifted_qmr_sym_b"
```
のようにすると（methodを4つの中から選択）、それに対応したソルバーが動作します。
method指定なし、または上記以外を入れた場合は、ハミルトニアンから自動的にbicgかcocgを選択します。

手法指定の順序は

- まずハミルトニアンからBiCG/COCGを設定
- namelist指定のパラメータがあればそちらで上書き

となっています。

**Comment by ykonishi** [comment]
ドキュメントに上記追加しました。
https://github.com/k-yoshimi/Komega/blob/qmr-devel/doc/software/ja/shiftk_format_ja.rst
https://github.com/k-yoshimi/Komega/blob/qmr-devel/doc/software/en/shiftk_format_en.rst

**Comment by ykonishi** [comment]
与えられた行列が複素エルミート行列の時にCOCG, QMR_SYM, QMR_SYM(B)を選択するとエラーメッセージを出して停止するようにshiftk_io.F90内のサブルーチンinput_parameter_cgを修正しました。
https://github.com/k-yoshimi/Komega/blob/qmr-devel/app/src/shiftk_io.F90

**Comment by k-yoshimi** [comment]
完了したのでclose.
